phpenv:
  links:
    - db:mysql
db:
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: KONFIO
  volumes:
    - ~/konfio/databases/konfio-no-data.sql:/docker-entrypoint-initdb.d/file.sql:ro
