camimos:
  image: webdevops/php-nginx:alpine-3-php7
  container_name: camimos
  volumes:
    - /Users/gandresibarra/Projects/Laravel/Camimos:/app
  environment:
    - WEB_DOCUMENT_INDEX=index.php
    - WEB_DOCUMENT_ROOT=/app/public/
    - APPLICATION_PATH=/app
  ports:
    - "3001:80"