laravel:
  image: webdevops/php-nginx:alpine-3-php7
  container_name: konfio_v3
  volumes:
    - /Users/gandresibarra/Projects/Konfio/konfio.v3:/app
  environment:
    - WEB_DOCUMENT_INDEX=index.php
    - WEB_DOCUMENT_ROOT=/app/public/
    - APPLICATION_PATH=/app
  ports:
    - "3000:80"